name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout your repository
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'  # You can use any other distribution if needed
    - name: Build with Ant
      run: ant build -buildfile build.xml  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: jar-file  
        path: dist/JarFileSizeCalculator.jar  # Path to the generated JAR file
